const active = [ 
    {
    "id" : "1",
    "status" : "2",
    "Reausition" : "RFQ-441",
     "PO" : "#911",
     "Date" : "4-5-2020",
     "Catg#" : {"Vigat" : "5" ,"Meat" : "2"},
     "Supplier" : "ahmed",
     "Payment Type" : "Cash",
    "payment Status" : "Today",
    "PO Status" : "2 Weeks ago",
    "PO status" : "3 Weeks ago",
     "Total" : "7",
     "paymentType" : "Cash"
    },
    {
        "id" : "3",
        "status" : "2",
        "Reausition" : "RFQ-443",
         "PO" : "#911",
         "Date" : "4-5-2020",
         "Catg#" : {"Vigat" : "4" ,"Meat" : "9"},
         "Supplier" : "Alkhatim",
         "Payment Type" : "Cash",
        "payment Status" : "2 days ago",
        "PO Status" : "1 Week ago",
        "PO status" : "2 Week ago",
         "Total" : "11",
         "paymentType" : "Cash"
        },
        {
        "id" : "4",
        "status" : "2",
        "Reausition" : "RFQ-443",
         "PO" : "#911",
         "Date" : "4-5-2020",
         "Catg#" : {"Vigat" : "4" ,"Meat" : "9"},
         "Supplier" : "musab",
         "Payment Type" : "Cash",
        "payment Status" : "2 days ago",
        "PO Status" : "1 Week ago",
        "PO status" : "2 Week ago",
         "Total" : "11",
         "paymentType" : "Cash"
        },
        {
            "id" : "7",
            "status" : "2",
            "Reausition" : "RFQ-443",
            "PO" : "#911",
            "Date" : "4-5-2020",
            "Catg#" : {"Vigat" : "4" ,"Meat" : "9"},
            "Supplier" : "osman",
            "Payment Type" : "Cash",
            "payment Status" : "5 days ago",
            "PO Status" : "1 Week ago",
            "PO status" : "2 Week ago",
            "Total" : "11",
            "paymentType" : "Cash"
            },
    {
    "id" : "2",
    "status" : "2",
    "Reausition" : "RFQ-442",
     "PO" : "#911",
     "Date" : "4-5-2020",
     "Catg#" : {"Vigat" : "3" ,"Meat" : "1"},
     "Supplier" : "musab",
     "Payment Type" : "Cash",
    "payment Status" : "2 Weeks ago",
    "PO Status" : "2 days ago",
    "PO status" : "2 days ago",
     "Total" : "4",
     "paymentType" : "Cash"
    },
   
    {
    "id" : "5",
    "status" : "2",
    "Reausition" : "RFQ-443",
     "PO" : "#911",
     "Date" : "4-5-2020",
     "Catg#" : {"Vigat" : "14" ,"Meat" : "9"},
     "Supplier" : "alkhatim",
     "Payment Type" : "Cash",
    "payment Status" : "2 Months ago",
    "PO Status" : "1 Week ago",
    "PO status" : "2 Week ago",
     "Total" : "23",
     "paymentType" : "Cash"
    },
    {
    "id" : "6",
    "status" : "2",
    "Reausition" : "RFQ-443",
    "PO" : "#911",
    "Date" : "4-5-2020",
    "Catg#" : {"Vigat" : "4" ,"Meat" : "9"},
    "Supplier" : "omer",
    "Payment Type" : "Cash",
    "payment Status" : "Month ago",
    "PO Status" : " yesturday",
    "PO status" : "2 Week ago",
        "Total" : "11",
        "paymentType" : "Cash"
    },
    
]
const inactive = [ {
   "id" : "4",
    "status" : "2",
    "Reausition" : "RFQ-441",
    "PO" : "#911",
    "Date" : "4-5-2020",
    "Catg#" : {"Vigat" : "4" ,"Meat" : "7"},
    "Supplier" : "musab",
    "Payment Type" : "Cash",
    "payment Status" : "2 Weeks ago",
    "PO Status" : " Today",
    "PO status" : "3 Weeks ago",
    "Total" : "8",
    "paymentType" : "Cash"
    },{
    "id" : "1",
    "status" : "2",
    "Reausition" : "RFQ-441",
     "PO" : "#911",
     "Date" : "4-5-2020",
    "Catg#" : {"Food" : 2 ,"Meat" : "3"},
     "Supplier" : "hashim",
     "Payment Type" : "Cash",
    "payment Status" : "Yesturday",
    "PO Status" : "April",
    "PO status" : "3 Weeks ago",
     "Total" : "8",
     "paymentType" : "Cash"
    },
    {
    "id" : "2",
    "status" : "2",
    "Reausition" : "RFQ-441",
    "PO" : "#911",
    "Date" : "4-5-2020",
    "Catg#" : {"Vigat" : "4" ,"Meat" : "7"},
    "Supplier" : "muhammed",
    "Payment Type" : "Cash",
    "payment Status" : "2 Weeks ago",
    "PO Status" : "2 Weeks ago",
    "PO status" : "3 Weeks ago",
    "Total" : "8",
    "paymentType" : "Cash"
    },
    {
    "id" : "3",
    "status" : "2",
    "Reausition" : "RFQ-441",
    "PO" : "#911",
    "Date" : "4-5-2020",
    "Catg#" : {"Vigat" : "4" ,"Meat" : "7"},
    "Supplier" : "omer",
    "Payment Type" : "Cash",
    "payment Status" : "Yesturday",
    "PO Status" : "Yesturday",
    "PO status" : "Yesturday",
    "Total" : "8",
    "paymentType" : "Cash"
    },

]

let data = { active, inactive}

export default data